General-Settings:
    Prefix: "&7[&6GUIShop&7] "
Inventory-Settings:
    Name: "     &6GUIShop!     "
    Size: 1
Sound-Settings:
    Buy-Sound: ITEM_PICKUP
    Sell-Sound: ITEM_BREAK
    Deny-Sound: VILLAGER_NO
Category-Settings:
    Blocks:
        Name: "Minecraft Blocks"
        Size: 2
        Icon: Grass
        Lore:
          - "&7Left click to open"
        Stock:
            Stone:
                #The name is not neccessary, the plugin will use the item name from Essentials if name is not set.
                Name: ""
                #This lore is not neccessary, the plugin will use an empty lore if this is not set.
                Lore:
                  - ""
                Buy-Price: 64
                Sell-Price: 24
                #This command is not neccessary, the plugin will use the item instead if command is not set.
                Command: "give %p% stone 1"
    Material:
        Name: "Minecraft Material"
        Size: 1
        Icon: Stick
        Lore:
          - "&7Left click to open"
        Stock:
            Coal:
                Name: ""
                Lore:
                  - ""
                Buy-Price: 16
                Sell-Price: 8
                Command: ""