name: GUIShop
main: com.aaomidi.dev.guishop.GUIShop
version: ${project.version}
author: aaomidi
authors: [aaomidi]
depend: [Vault, Essentials]
commands:
  shop:
    description: Access shop.
    usage: /shop
